#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

cd "$SCRIPT_HOME"

case "$1" in
  start)
      docker-compose up --force-recreate bc_registries worksafe_bc
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      echo -e "\nBuilding libindy image ..."
      docker build \
          -t 'libindy' \
          -f 'LibIndy-Dockerfile' \
          .

      echo -e "\nBuilding python-libindy image ..."
      docker build \
          -t 'python-libindy' \
          -f 'Python-LibIndy-Dockerfile' \
          .

      echo -e "\nBuilding permitify image ..."
      docker build \
          -t 'permitify' \
          -f 'Permitify-Dockerfile' \
          .
    ;;
  rebuild)
      echo -e "\nRebuilding libindy image ..."
      docker build \
          --no-cache \
          -t 'libindy' \
          -f 'LibIndy-Dockerfile' \
          .
      
      echo -e "\nRebuilding python-libindy image ..."
      docker build \
          --no-cache \
          -t 'python-libindy' \
          -f 'Python-LibIndy-Dockerfile' \
          .

      echo -e "\nRebuilding permitify image ..."
      docker build \
          --no-cache \
          -t 'permitify' \
          -f 'Permitify-Dockerfile' \
          .
    ;;
  shell)
      docker-compose run web bash
    ;;
  *)
    echo $"Usage: $0 {start|stop|build|rebuild}"
esac

( cd - ) > /dev/null