#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

cd "$SCRIPT_HOME"

case "$1" in
  start)
      docker-compose up --force-recreate bc_registries worksafe_bc
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      docker-compose build
    ;;
  rebuild)
      docker-compose build --no-cache
    ;;
  shell)
      docker-compose run web bash
    ;;
  *)
    echo $"Usage: $0 {start|stop|build|rebuild}"
esac

( cd - ) > /dev/null